---
# config 
nodes:
  - name: master.devops.org
    ip: 192.168.33.10
    cpus: 1
    memory: 1024
    shell: bootstrap.sh
  - name: node01.devops.org
    ip: 192.168.33.11
    cpus: 1
    memory: 1024
    shell: bootstrap.sh
  - name: node02.devops.org
    ip: 192.168.33.12
    cpus: 1
    memory: 1024
    shell: bootstrap.sh
